/** Real-device pixel checks. Run on a dedicated WebGPU device, not a host spy.
 * This fixture uploads/reads pixels; production bloom/postprocessing never does.
 * Expected constant-image results are analytic, not generated by the shaders.
 */
import { createGpuAnimationBloom } from './animation_bloom.mjs';
import { createGpuAnimationPostprocessor } from './animation_postprocess.mjs';

const assert = (condition, message) => { if (!condition) throw new Error(message); };
function half(value) {
  const sign = value < 0 || Object.is(value, -0) ? 0x8000 : 0, x = Math.abs(value);
  if (x === 0) return sign;
  assert(Number.isFinite(x) && x <= 65504, 'Fixture radiance must fit finite binary16');
  let e = Math.floor(Math.log2(x));
  const scaled = e < -14 ? x * 2 ** 24 : x / 2 ** (e - 10), lo = Math.floor(scaled), fraction = scaled - lo;
  let m = lo + (fraction > 0.5 || (fraction === 0.5 && lo % 2) ? 1 : 0);
  if (e < -14) return sign | m;
  if (m === 2048) { e++; m = 1024; }
  return sign | ((e + 15) << 10) | (m - 1024);
}
function fromHalf(bits) {
  const sign = bits & 0x8000 ? -1 : 1, exponent = (bits >> 10) & 31, mantissa = bits & 1023;
  return sign * (exponent === 0 ? mantissa * 2 ** -24 : exponent === 31 ? (mantissa ? NaN : Infinity) : (1 + mantissa / 1024) * 2 ** (exponent - 15));
}
export async function runAnimationBloomBrowserChecks(device) {
  assert(typeof GPUDevice !== 'undefined' && device instanceof GPUDevice, 'NATIVE_DEVICE_REQUIRED: host spies are not GPU execution evidence');
  const owned = [], checks = [];
  const own = value => { owned.push(value); return value; };
  const target = (width, height, format = 'rgba16float') => own(device.createTexture({
    size: { width, height }, format, usage: GPUTextureUsage.TEXTURE_BINDING | GPUTextureUsage.RENDER_ATTACHMENT | GPUTextureUsage.COPY_SRC,
  }));
  function source(width, height, color) {
    const texture = own(device.createTexture({ size: { width, height }, format: 'rgba16float', usage: GPUTextureUsage.COPY_DST | GPUTextureUsage.TEXTURE_BINDING }));
    const bytesPerRow = Math.ceil(width * 8 / 256) * 256, bytes = new ArrayBuffer(bytesPerRow * height), view = new DataView(bytes);
    for (let y = 0; y < height; y++) for (let x = 0; x < width; x++) {
      const rgba = typeof color === 'function' ? color(x, y) : color;
      for (let c = 0; c < 4; c++) view.setUint16(y * bytesPerRow + x * 8 + c * 2, half(rgba[c]), true);
    }
    device.queue.writeTexture({ texture }, bytes, { bytesPerRow, rowsPerImage: height }, { width, height });
    return texture;
  }
  async function read(texture) {
    const stride = texture.format === 'rgba16float' ? 8 : 4, bytesPerRow = Math.ceil(texture.width * stride / 256) * 256;
    const buffer = device.createBuffer({ size: bytesPerRow * texture.height, usage: GPUBufferUsage.COPY_DST | GPUBufferUsage.MAP_READ });
    try {
      const encoder = device.createCommandEncoder();
      encoder.copyTextureToBuffer({ texture }, { buffer, bytesPerRow, rowsPerImage: texture.height }, { width: texture.width, height: texture.height });
      device.queue.submit([encoder.finish()]); await buffer.mapAsync(GPUMapMode.READ);
      const data = new DataView(buffer.getMappedRange()), values = [];
      for (let y = 0; y < texture.height; y++) for (let x = 0; x < texture.width; x++) for (let c = 0; c < 4; c++) {
        const offset = y * bytesPerRow + x * stride;
        values.push(stride === 8 ? fromHalf(data.getUint16(offset + c * 2, true)) : data.getUint8(offset + c));
      }
      buffer.unmap(); return values;
    } finally { buffer.destroy(); }
  }
  const constant = (values, rgba, tolerance = 0.003) => values.forEach((value, i) => assert(Number.isFinite(value) && Math.abs(value - rgba[i % 4]) <= tolerance, `Channel ${i}: ${value}, expected ${rgba[i % 4]}`));
  async function check(name, operation) {
    device.pushErrorScope('validation');
    let failure;
    try { await operation(); await device.queue.onSubmittedWorkDone(); } catch (error) { failure = error; }
    const invalid = await device.popErrorScope();
    if (failure) throw failure;
    assert(!invalid, invalid?.message ?? 'Native validation failure');
    checks.push(name);
  }
  try {
    const bloom = own(await createGpuAnimationBloom(device, { levels: 3, softKnee: 0 }));
    await check('below-threshold radiance stays unchanged', async () => {
      const input = source(8, 8, [0.5, 0.5, 0.5, 1]), out = target(8, 8);
      bloom.render({ source: input, target: out }); await bloom.whenIdle(); constant(await read(out), [0.5, 0.5, 0.5, 1]);
    });
    await check('constant HDR 4 plus thresholded bloom 3 equals 7 at every pyramid scale', async () => {
      const input = source(16, 8, [4, 4, 4, 1]), out = target(16, 8);
      bloom.render({ source: input, target: out }); await bloom.whenIdle(); constant(await read(out), [7, 7, 7, 1], 0.01);
    });
    await check('soft-knee contribution at threshold is one quarter', async () => {
      const input = source(5, 3, [1, 1, 1, 1]), out = target(5, 3);
      bloom.render({ source: input, target: out, softKnee: 1 }); await bloom.whenIdle(); constant(await read(out), [1.25, 1.25, 1.25, 1]);
    });
    await check('zero-strength bypass preserves negative radiance and source alpha', async () => {
      const input = source(3, 1, [-0.5, 3, 1, 0.25]), out = target(3, 1);
      bloom.render({ source: input, target: out, strength: 0 }); await bloom.whenIdle(); constant(await read(out), [-0.5, 3, 1, 0.25], 0);
    });
    await check('an isolated HDR highlight produces nonzero neighboring glow', async () => {
      const input = source(17, 9, (x, y) => x === 8 && y === 4 ? [16, 16, 16, 1] : [0, 0, 0, 1]), out = target(17, 9);
      bloom.render({ source: input, target: out }); await bloom.whenIdle(); const pixels = await read(out);
      assert(pixels[(4 * 17 + 8) * 4] > 16, 'Bright source was not retained');
      assert(pixels[(4 * 17 + 6) * 4] > 0, 'No blur spread to a dark neighboring pixel');
      assert(pixels.every(Number.isFinite), 'Nonfinite bloom result');
    });
    await check('odd right/bottom border highlights are included', async () => {
      const input = source(5, 3, (x, y) => x === 4 && y === 2 ? [16, 16, 16, 1] : [0, 0, 0, 1]), out = target(5, 3);
      bloom.render({ source: input, target: out }); await bloom.whenIdle(); const pixels = await read(out);
      assert(pixels[(2 * 5 + 4) * 4] > 16 && pixels[(2 * 5 + 3) * 4] > 0, 'Odd border was discarded');
    });
    await check('successive queued submissions retain distinct uniform values', async () => {
      const input = source(8, 8, [4, 4, 4, 1]), a = target(8, 8), b = target(8, 8);
      bloom.render({ source: input, target: a, strength: 1 }); bloom.render({ source: input, target: b, strength: 2 });
      await bloom.whenIdle(); constant(await read(a), [7, 7, 7, 1], 0.01); constant(await read(b), [10, 10, 10, 1], 0.02);
    });
    const post = own(await createGpuAnimationPostprocessor(device, {
      bloom: { levels: 3, softKnee: 0 }, output: { format: 'rgba8unorm', outputColorSpace: 'linear', toneMapping: 'reinhard' },
    }));
    await check('bloom is composed before Reinhard mapping, not after display clipping', async () => {
      const input = source(8, 8, [4, 4, 4, 1]), out = target(8, 8, 'rgba8unorm');
      post.render({ source: input, target: out }); await post.whenIdle(); constant(await read(out), [223, 223, 223, 255], 1);
    });
    await check('managed HDR/depth scene attachments feed native bloom and output', async () => {
      // Native clear-source seam, not a claim of full glTF renderer integration.
      const scene = {
        render(frame) {
          const encoder = device.createCommandEncoder();
          const pass = encoder.beginRenderPass({ colorAttachments: [{ view: frame.colorView, loadOp: 'clear', storeOp: 'store', clearValue: frame.clearColor }],
            depthStencilAttachment: { view: frame.depthView, depthLoadOp: 'clear', depthStoreOp: 'store', depthClearValue: 1 } });
          pass.end(); device.queue.submit([encoder.finish()]); return this;
        }, whenIdle() { return device.queue.onSubmittedWorkDone(); },
      };
      const out = target(8, 8, 'rgba8unorm'); post.renderScene(scene, { target: out, frame: { clearColor: [4, 4, 4, 1] } });
      await post.whenIdle(); constant(await read(out), [223, 223, 223, 255], 1);
    });
    return Object.freeze({ format: 'f3d-animation-bloom-browser-v1', execution: 'native-webgpu', passed: checks.length, checks: Object.freeze(checks) });
  } finally { for (const resource of owned.reverse()) { if (typeof resource.dispose === 'function') resource.dispose(); else resource.destroy(); } }
}
