/**
 * static_submission_generator.mjs - Build-time static JS draw generator (§16.7, §21, tmt.5)
 *
 * Emits an ordinary static ESM function with precomputed dynamic uniform offsets
 * for fixed draw submissions, avoiding runtime eval/new Function and reflection.
 */

import fs from 'node:fs';
import path from 'node:path';

/**
 * Generates the source code of a static ESM module for fixed draw submission.
 * @param {number} [drawCount=4000] Number of draws to precompute.
 * @param {number} [offsetAlignment=256] Dynamic uniform buffer offset alignment in bytes.
 * @param {number} [firstDraw=0] First source transform index, for a generated direct tail.
 * @returns {string} Emitted JavaScript module source.
 */
export function generateStaticSubmissionSource(drawCount = 4000, offsetAlignment = 256, firstDraw = 0) {
  if (!Number.isSafeInteger(drawCount) || drawCount <= 0) {
    throw new RangeError(`drawCount must be a positive safe integer, got ${drawCount}`);
  }
  if (!Number.isSafeInteger(offsetAlignment) || offsetAlignment <= 0 ||
      !Number.isSafeInteger(firstDraw) || firstDraw < 0 ||
      (firstDraw + drawCount - 1) * offsetAlignment > 0xffffffff) {
    throw new RangeError("Static submission offsets must be nonnegative u32 values with a positive integer stride");
  }
  const lines = [
    '// Generated by static_submission_generator.mjs; do not edit directly.',
    `// Precomputed static WebGPU draw submission for ${drawCount} draws with ${offsetAlignment}B dynamic offsets.`,
    `export function executeStaticSubmission${drawCount}(pass, bindGroup) {`
  ];
  for (let i = 0; i < drawCount; i++) {
    const offset = (firstDraw + i) * offsetAlignment;
    lines.push(`  pass.setBindGroup(0, bindGroup, [${offset}]);`);
    lines.push('  pass.draw(3, 1, 0, 0);');
  }
  lines.push('}\n');
  return lines.join('\n');
}

/**
 * Emits the generated static submission module to the target output directory.
 * @param {string} outPath Destination file path.
 * @param {number} [drawCount=4000]
 * @returns {{ path: string, byteLength: number, lineCount: number }}
 */
export function emitStaticSubmissionModule(outPath, drawCount = 4000) {
  const code = generateStaticSubmissionSource(drawCount);
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, code, 'utf-8');
  return {
    path: outPath,
    byteLength: Buffer.byteLength(code, 'utf-8'),
    lineCount: code.split('\n').length - 1
  };
}

// CLI entry point for RCH execution
if (process.argv[1] && process.argv[1].endsWith('static_submission_generator.mjs')) {
  const targetDir = process.argv[2] || path.resolve('out/browser-probe');
  const targetPath = path.join(targetDir, 'static_submission_4000.js');
  const meta = emitStaticSubmissionModule(targetPath, 4000);
  console.log(`[static_submission_generator] Emitted ${meta.lineCount} lines (${meta.byteLength} bytes) to ${meta.path}`);
  const tailPath = path.join(targetDir, 'static_submission_tail4.js');
  const tailCode = generateStaticSubmissionSource(4, 256, 3996);
  fs.writeFileSync(tailPath, tailCode, 'utf-8');
  console.log(`[static_submission_generator] Emitted ${Buffer.byteLength(tailCode)} bytes to ${tailPath}`);
}
