/**
 * static_submission_generator.mjs - Build-time static JS draw generator (§16.7, §21, tmt.5)
 *
 * Emits an ordinary static ESM function with precomputed dynamic uniform offsets
 * for fixed draw submissions, avoiding runtime eval/new Function and reflection.
 */

import fs from 'node:fs';
import path from 'node:path';

/**
 * Generates the source code of a static ESM module for fixed draw submission.
 * @param {number} [drawCount=4000] Number of draws to precompute.
 * @param {number} [offsetAlignment=256] Dynamic uniform buffer offset alignment in bytes.
 * @param {number} [firstDraw=0] First source transform index, for a generated direct tail.
 * @returns {string} Emitted JavaScript module source.
 */
export function generateStaticSubmissionSource(drawCount = 4000, offsetAlignment = 256, firstDraw = 0) {
  if (!Number.isSafeInteger(drawCount) || drawCount <= 0) {
    throw new RangeError(`drawCount must be a positive safe integer, got ${drawCount}`);
  }
  if (!Number.isSafeInteger(offsetAlignment) || offsetAlignment <= 0 ||
      !Number.isSafeInteger(firstDraw) || firstDraw < 0 ||
      (firstDraw + drawCount - 1) * offsetAlignment > 0xffffffff) {
    throw new RangeError("Static submission offsets must be nonnegative u32 values with a positive integer stride");
  }
  const lines = [
    '// Generated by static_submission_generator.mjs; do not edit directly.',
    `// Precomputed static WebGPU draw submission for ${drawCount} draws with ${offsetAlignment}B dynamic offsets.`,
    `export function executeStaticSubmission${drawCount}(pass, bindGroup) {`
  ];
  for (let i = 0; i < drawCount; i++) {
    const offset = (firstDraw + i) * offsetAlignment;
    lines.push(`  pass.setBindGroup(0, bindGroup, [${offset}]);`);
    lines.push('  pass.draw(3, 1, 0, 0);');
  }
  lines.push('}\n');
  return lines.join('\n');
}

/**
 * Emits the generated static submission module to the target output directory.
 * @param {string} outPath Destination file path.
 * @param {number} [drawCount=4000]
 * @returns {{ path: string, byteLength: number, lineCount: number }}
 */
export function emitStaticSubmissionModule(outPath, drawCount = 4000) {
  const code = generateStaticSubmissionSource(drawCount);
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, code, 'utf-8');
  return {
    path: outPath,
    byteLength: Buffer.byteLength(code, 'utf-8'),
    lineCount: code.split('\n').length - 1
  };
}

/**
 * Generates the source code of a static ESM module for fixed persistent packed buffer upload (§16.7, §21, tmt.5, root contract 20934).
 *
 * Emits an ordinary static ESM function that:
 * - INIT once: creates source buffer 610 (COPY_SRC|COPY_DST) and two destination slots 611 and 612 (MAP_READ|COPY_DST), each 48*N bytes.
 * - FRAME (no creation): writes 48*N packed bytes to buffer 610, then one opcode 20 copy 610 -> 611 or 612 (alternating slot per frame).
 * - Guards: record count must match init N (4000); destination must be 611 or 612; usage is COPY_SRC|COPY_DST, NOT STORAGE.
 *
 * @param {number} [recordCount=4000] Number of packed 48B AffineRows records.
 * @param {number} [recordBytes=48] Size of each record in bytes.
 * @returns {string} Emitted JavaScript module source.
 */
export function generateStaticPackedUploadSource(recordCount = 4000, recordBytes = 48) {
  if (!Number.isSafeInteger(recordCount) || recordCount <= 0) {
    throw new RangeError(`recordCount must be a positive safe integer, got ${recordCount}`);
  }
  if (!Number.isSafeInteger(recordBytes) || recordBytes <= 0 || recordBytes % 4 !== 0) {
    throw new RangeError(`recordBytes must be a positive safe integer multiple of 4, got ${recordBytes}`);
  }
  const totalBytes = recordCount * recordBytes;
  if (!Number.isSafeInteger(totalBytes) || totalBytes > 0xffffffff) {
    throw new RangeError(`totalBytes (${totalBytes}) exceeds u32 limit`);
  }

  const lines = [
    '// Generated by static_submission_generator.mjs; do not edit directly.',
    `// Precomputed static WebGPU persistent packed upload for ${recordCount} records (${totalBytes} bytes, root contract 20934).`,
    '',
    `export const PACKED_RECORD_COUNT = ${recordCount};`,
    `export const PACKED_RECORD_BYTES = ${recordBytes};`,
    `export const PACKED_TOTAL_BYTES = ${totalBytes};`,
    `export const SOURCE_BUFFER_ID = 610;`,
    `export const DESTINATION_BUFFER_IDS = [611, 612];`,
    `export const DESTINATION_SLOT_0 = 611;`,
    `export const DESTINATION_SLOT_1 = 612;`,
    '',
    `/**`,
    ` * Initializes persistent buffers once (§16.7, §21, tmt.5, root contract 20934):`,
    ` * - Source buffer 610: COPY_SRC|COPY_DST, size ${totalBytes}B`,
    ` * - Two destination slots 611 and 612: MAP_READ|COPY_DST, size ${totalBytes}B each`,
    ` * @param {GPUDevice} device`,
    ` * @returns {{ srcBuffer: GPUBuffer, dstBuffer611: GPUBuffer, dstBuffer612: GPUBuffer, dstBuffers: Object }}`,
    ` */`,
    `export function initStaticPackedBuffers${recordCount}(device) {`,
    `  if (!device || !device.createBuffer) throw new TypeError("Valid GPUDevice required");`,
    `  const usageSrc = GPUBufferUsage.COPY_SRC | GPUBufferUsage.COPY_DST;`,
    `  const usageDst = GPUBufferUsage.MAP_READ | GPUBufferUsage.COPY_DST;`,
    `  const srcBuffer = device.createBuffer({`,
    `    label: "f3d-static-packed-src-610",`,
    `    size: ${totalBytes},`,
    `    usage: usageSrc,`,
    `  });`,
    `  const dstBuffer611 = device.createBuffer({`,
    `    label: "f3d-static-packed-dst-611",`,
    `    size: ${totalBytes},`,
    `    usage: usageDst,`,
    `  });`,
    `  const dstBuffer612 = device.createBuffer({`,
    `    label: "f3d-static-packed-dst-612",`,
    `    size: ${totalBytes},`,
    `    usage: usageDst,`,
    `  });`,
    `  return {`,
    `    srcBuffer,`,
    `    dstBuffer611,`,
    `    dstBuffer612,`,
    `    dstBuffers: { 611: dstBuffer611, 612: dstBuffer612 },`,
    `  };`,
    `}`,
    '',
    `/**`,
    ` * Executes static upload of ${recordCount} packed AffineRows records (${totalBytes} bytes)`,
    ` * into persistent buffer 610 via device.queue.writeBuffer (no buffer creation).`,
    ` * Guard: record count must match init N (${recordCount} records, ${totalBytes} bytes).`,
    ` * @param {GPUDevice} device`,
    ` * @param {GPUBuffer} srcBuffer`,
    ` * @param {Float32Array|Uint8Array|ArrayBufferView} data`,
    ` * @param {number} [bufferOffset=0]`,
    ` */`,
    `export function executeStaticPackedUpload${recordCount}(device, srcBuffer, data, bufferOffset = 0) {`,
    `  if (!device || !device.queue) throw new TypeError("Valid GPUDevice required");`,
    `  if (!srcBuffer) throw new TypeError("Valid srcBuffer required");`,
    `  if (!ArrayBuffer.isView(data)) {`,
    `    throw new TypeError("data must be an ArrayBuffer view (e.g. Float32Array, Uint8Array)");`,
    `  }`,
    `  if (data.byteLength !== ${totalBytes}) {`,
    `    throw new RangeError(\`record count must match the init N (${recordCount} records = ${totalBytes} bytes, got \${data.byteLength})\`);`,
    `  }`,
    `  device.queue.writeBuffer(srcBuffer, bufferOffset, data);`,
    `}`,
    '',
    `/**`,
    ` * Records static buffer copy 610 -> 611 or 612 for ${recordCount} records (${totalBytes} bytes).`,
    ` * Guard: destination must be 611 or 612.`,
    ` * @param {GPUCommandEncoder} encoder`,
    ` * @param {GPUBuffer} srcBuffer`,
    ` * @param {GPUBuffer} dstBuffer`,
    ` * @param {number} [destinationId=611]`,
    ` * @param {number} [srcOffset=0]`,
    ` * @param {number} [dstOffset=0]`,
    ` */`,
    `export function recordStaticPackedBufferCopy${recordCount}(encoder, srcBuffer, dstBuffer, destinationId = 611, srcOffset = 0, dstOffset = 0) {`,
    `  if (!encoder) throw new TypeError("Valid GPUCommandEncoder required");`,
    `  if (!srcBuffer || !dstBuffer) throw new TypeError("Valid srcBuffer and dstBuffer required");`,
    `  if (destinationId !== 611 && destinationId !== 612) {`,
    `    throw new RangeError(\`destination must be 611 or 612, got \${destinationId}\`);`,
    `  }`,
    `  encoder.copyBufferToBuffer(srcBuffer, srcOffset, dstBuffer, dstOffset, ${totalBytes});`,
    `}`,
    '',
    `/**`,
    ` * Executes a per-frame persistent packed upload submission (no buffer creation):`,
    ` * WriteBuffer 610 offset 0 (${totalBytes}B) -> copy 610 -> 611/612 -> queue.submit.`,
    ` * Guards: record count must match init N (${recordCount}); destination must be 611 or 612.`,
    ` * @param {GPUDevice} device`,
    ` * @param {GPUBuffer} srcBuffer`,
    ` * @param {GPUBuffer} dstBuffer`,
    ` * @param {Float32Array|Uint8Array|ArrayBufferView} data`,
    ` * @param {number} [destinationId=611] - 611 or 612`,
    ` * @param {Object} [timingRecord=null]`,
    ` * @returns {Promise<void>}`,
    ` */`,
    `export function executeStaticPackedSubmission${recordCount}(device, srcBuffer, dstBuffer, data, destinationId = 611, timingRecord = null) {`,
    `  if (destinationId !== 611 && destinationId !== 612) {`,
    `    throw new RangeError(\`destination must be 611 or 612, got \${destinationId}\`);`,
    `  }`,
    `  const t0 = timingRecord ? performance.now() : 0;`,
    `  executeStaticPackedUpload${recordCount}(device, srcBuffer, data);`,
    `  const encoder = device.createCommandEncoder();`,
    `  recordStaticPackedBufferCopy${recordCount}(encoder, srcBuffer, dstBuffer, destinationId);`,
    `  const commandBuffer = encoder.finish();`,
    `  const tFinish = timingRecord ? performance.now() : 0;`,
    `  const tSubmitStart = timingRecord ? performance.now() : 0;`,
    `  device.queue.submit([commandBuffer]);`,
    `  const tSubmitEnd = timingRecord ? performance.now() : 0;`,
    `  if (timingRecord) {`,
    `    timingRecord._t0 = t0;`,
    `    timingRecord._tFinish = tFinish;`,
    `    timingRecord._tSubmitStart = tSubmitStart;`,
    `    timingRecord._tSubmitEnd = tSubmitEnd;`,
    `  }`,
    `  return device.queue.onSubmittedWorkDone();`,
    `}`,
    '',
    `/**`,
    ` * Creates a two-frame credit loop compatible runner for static persistent packed uploads.`,
    ` * Alternates destination slot between 611 and 612 per frame (max 2 in flight).`,
    ` * @param {GPUDevice} device`,
    ` * @param {Object} buffers - Pre-allocated { srcBuffer, dstBuffer611, dstBuffer612 } from initStaticPackedBuffers${recordCount}`,
    ` */`,
    `export function createStaticPackedUploadRunner${recordCount}(device, buffers) {`,
    `  if (!device || !device.queue) throw new TypeError("Valid GPUDevice required");`,
    `  if (!buffers || !buffers.srcBuffer || !buffers.dstBuffer611 || !buffers.dstBuffer612) {`,
    `    throw new TypeError("Pre-allocated buffers object with srcBuffer, dstBuffer611, and dstBuffer612 required (call initStaticPackedBuffers${recordCount}(device) first)");`,
    `  }`,
    `  const src = buffers.srcBuffer;`,
    `  const dst611 = buffers.dstBuffer611;`,
    `  const dst612 = buffers.dstBuffer612;`,
    `  const dstMap = buffers.dstBuffers || { 611: dst611, 612: dst612 };`,
    '',
    `  let currentFrameIndex = 0;`,
    `  let lastDestinationBufferId = 611;`,
    '',
    `  function submitFrame(data, timingRecord = null, targetDestinationId = null) {`,
    `    let dstId;`,
    `    if (targetDestinationId !== null) {`,
    `      if (targetDestinationId === 0) dstId = 611;`,
    `      else if (targetDestinationId === 1) dstId = 612;`,
    `      else dstId = targetDestinationId;`,
    `      if (dstId !== 611 && dstId !== 612) {`,
    `        throw new RangeError(\`destination must be 611 or 612, got \${targetDestinationId}\`);`,
    `      }`,
    `    } else {`,
    `      dstId = (currentFrameIndex % 2 === 0) ? 611 : 612;`,
    `    }`,
    `    const targetDst = dstMap[dstId];`,
    `    lastDestinationBufferId = dstId;`,
    `    currentFrameIndex++;`,
    `    return executeStaticPackedSubmission${recordCount}(device, src, targetDst, data, dstId, timingRecord);`,
    `  }`,
    '',
    `  return {`,
    `    device,`,
    `    srcBuffer: src,`,
    `    dstBuffer611: dst611,`,
    `    dstBuffer612: dst612,`,
    `    dstBuffers: dstMap,`,
    `    recordCount: ${recordCount},`,
    `    byteLength: ${totalBytes},`,
    `    srcBufferId: 610,`,
    `    dstBufferIds: [611, 612],`,
    `    get currentFrameIndex() { return currentFrameIndex; },`,
    `    get lastDestinationBufferId() { return lastDestinationBufferId; },`,
    `    submit: (data) => submitFrame(data, null, null),`,
    `    submitFrame,`,
    `    readback: async (slotOrId = null) => {`,
    `      let dstId;`,
    `      if (slotOrId === null) dstId = lastDestinationBufferId;`,
    `      else if (slotOrId === 0) dstId = 611;`,
    `      else if (slotOrId === 1) dstId = 612;`,
    `      else dstId = slotOrId;`,
    `      if (dstId !== 611 && dstId !== 612) {`,
    `        throw new RangeError(\`destination must be 611 or 612, got \${slotOrId}\`);`,
    `      }`,
    `      const b = dstMap[dstId];`,
    `      await b.mapAsync(GPUMapMode.READ, 0, ${totalBytes});`,
    `      const mapped = b.getMappedRange(0, ${totalBytes});`,
    `      const copy = new Uint8Array(mapped.slice(0));`,
    `      b.unmap();`,
    `      return copy;`,
    `    },`,
    `    destroy: () => {`,
    `      src.destroy();`,
    `      dst611.destroy();`,
    `      dst612.destroy();`,
    `    },`,
    `  };`,
    `}`,
    '',
    `export const initStaticPackedBuffers = initStaticPackedBuffers${recordCount};`,
    `export const executeStaticPackedUpload = executeStaticPackedUpload${recordCount};`,
    `export const recordStaticPackedBufferCopy = recordStaticPackedBufferCopy${recordCount};`,
    `export const executeStaticPackedSubmission = executeStaticPackedSubmission${recordCount};`,
    `export const createStaticPackedUploadRunner = createStaticPackedUploadRunner${recordCount};`,
    ''
  ];
  return lines.join('\n');
}

/**
 * Emits the generated static packed upload module to the target output directory.
 * @param {string} outPath Destination file path.
 * @param {number} [recordCount=4000]
 * @param {number} [recordBytes=48]
 * @returns {{ path: string, byteLength: number, lineCount: number }}
 */
export function emitStaticPackedUploadModule(outPath, recordCount = 4000, recordBytes = 48) {
  const code = generateStaticPackedUploadSource(recordCount, recordBytes);
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, code, 'utf-8');
  return {
    path: outPath,
    byteLength: Buffer.byteLength(code, 'utf-8'),
    lineCount: code.split('\n').length - 1
  };
}

/**
 * Initializes persistent buffers once (§16.7, §21, tmt.5, root contract 20934):
 * - Source buffer 610: COPY_SRC|COPY_DST, size 48*N
 * - Two destination slots 611 and 612: MAP_READ|COPY_DST, size 48*N each
 * @param {GPUDevice} device
 * @param {number} [recordCount=4000]
 * @param {number} [recordBytes=48]
 */
export function initStaticPackedBuffers(device, recordCount = 4000, recordBytes = 48) {
  if (!device || !device.createBuffer) throw new TypeError("Valid GPUDevice required");
  const totalBytes = recordCount * recordBytes;
  const usageSrc = GPUBufferUsage.COPY_SRC | GPUBufferUsage.COPY_DST;
  const usageDst = GPUBufferUsage.MAP_READ | GPUBufferUsage.COPY_DST;
  const srcBuffer = device.createBuffer({
    label: "f3d-static-packed-src-610",
    size: totalBytes,
    usage: usageSrc,
  });
  const dstBuffer611 = device.createBuffer({
    label: "f3d-static-packed-dst-611",
    size: totalBytes,
    usage: usageDst,
  });
  const dstBuffer612 = device.createBuffer({
    label: "f3d-static-packed-dst-612",
    size: totalBytes,
    usage: usageDst,
  });
  return {
    srcBuffer,
    dstBuffer611,
    dstBuffer612,
    dstBuffers: { 611: dstBuffer611, 612: dstBuffer612 },
  };
}

/**
 * Direct runtime execution helper for static persistent packed upload.
 * Guard: record count must match init N.
 * @param {GPUDevice} device
 * @param {GPUBuffer} srcBuffer
 * @param {Float32Array|Uint8Array|ArrayBufferView} data
 * @param {number} [recordCount=4000]
 * @param {number} [recordBytes=48]
 * @param {number} [bufferOffset=0]
 */
export function executeStaticPackedUpload(device, srcBuffer, data, recordCount = 4000, recordBytes = 48, bufferOffset = 0) {
  if (!device || !device.queue) throw new TypeError("Valid GPUDevice required");
  if (!srcBuffer) throw new TypeError("Valid srcBuffer required");
  const totalBytes = recordCount * recordBytes;
  if (!ArrayBuffer.isView(data)) {
    throw new TypeError("data must be an ArrayBuffer view (e.g. Float32Array, Uint8Array)");
  }
  if (data.byteLength !== totalBytes) {
    throw new RangeError(`record count must match the init N (${recordCount} records = ${totalBytes} bytes, got ${data.byteLength})`);
  }
  device.queue.writeBuffer(srcBuffer, bufferOffset, data);
}

/**
 * Direct runtime execution helper for recording static packed buffer copy.
 * Guard: destination must be 611 or 612.
 * @param {GPUCommandEncoder} encoder
 * @param {GPUBuffer} srcBuffer
 * @param {GPUBuffer} dstBuffer
 * @param {number} [destinationId=611]
 * @param {number} [recordCount=4000]
 * @param {number} [recordBytes=48]
 * @param {number} [srcOffset=0]
 * @param {number} [dstOffset=0]
 */
export function recordStaticPackedBufferCopy(encoder, srcBuffer, dstBuffer, destinationId = 611, recordCount = 4000, recordBytes = 48, srcOffset = 0, dstOffset = 0) {
  if (!encoder) throw new TypeError("Valid GPUCommandEncoder required");
  if (!srcBuffer || !dstBuffer) throw new TypeError("Valid srcBuffer and dstBuffer required");
  if (destinationId !== 611 && destinationId !== 612) {
    throw new RangeError(`destination must be 611 or 612, got ${destinationId}`);
  }
  encoder.copyBufferToBuffer(srcBuffer, srcOffset, dstBuffer, dstOffset, recordCount * recordBytes);
}

/**
 * Direct runtime execution helper for per-frame packed submission.
 * Guards: record count must match init N; destination must be 611 or 612.
 * @param {GPUDevice} device
 * @param {GPUBuffer} srcBuffer
 * @param {GPUBuffer} dstBuffer
 * @param {Float32Array|Uint8Array|ArrayBufferView} data
 * @param {number} [destinationId=611]
 * @param {number} [recordCount=4000]
 * @param {number} [recordBytes=48]
 * @param {Object} [timingRecord=null]
 * @returns {Promise<void>}
 */
export function executeStaticPackedSubmission(device, srcBuffer, dstBuffer, data, destinationId = 611, recordCount = 4000, recordBytes = 48, timingRecord = null) {
  if (destinationId !== 611 && destinationId !== 612) {
    throw new RangeError(`destination must be 611 or 612, got ${destinationId}`);
  }
  const t0 = timingRecord ? performance.now() : 0;
  executeStaticPackedUpload(device, srcBuffer, data, recordCount, recordBytes);
  const encoder = device.createCommandEncoder();
  recordStaticPackedBufferCopy(encoder, srcBuffer, dstBuffer, destinationId, recordCount, recordBytes);
  const commandBuffer = encoder.finish();
  const tFinish = timingRecord ? performance.now() : 0;
  const tSubmitStart = timingRecord ? performance.now() : 0;
  device.queue.submit([commandBuffer]);
  const tSubmitEnd = timingRecord ? performance.now() : 0;
  if (timingRecord) {
    timingRecord._t0 = t0;
    timingRecord._tFinish = tFinish;
    timingRecord._tSubmitStart = tSubmitStart;
    timingRecord._tSubmitEnd = tSubmitEnd;
  }
  return device.queue.onSubmittedWorkDone();
}

/**
 * Direct runtime execution helper for creating a persistent packed upload runner.
 * Alternates destination slots between 611 and 612 per frame.
 * @param {GPUDevice} device
 * @param {number} [recordCount=4000]
 * @param {number} [recordBytes=48]
 * @param {Object} [buffers=null]
 */
export function createStaticPackedUploadRunner(device, recordCount = 4000, recordBytes = 48, buffers = null) {
  if (!device || !device.queue) throw new TypeError("Valid GPUDevice required");
  let resolvedBuffers = buffers;
  let resolvedCount = recordCount;
  let resolvedBytes = recordBytes;
  if (recordCount && typeof recordCount === "object" && recordCount.srcBuffer) {
    resolvedBuffers = recordCount;
    resolvedCount = 4000;
    resolvedBytes = 48;
  }
  if (!resolvedBuffers || !resolvedBuffers.srcBuffer || !resolvedBuffers.dstBuffer611 || !resolvedBuffers.dstBuffer612) {
    throw new TypeError("Pre-allocated buffers object with srcBuffer, dstBuffer611, and dstBuffer612 required (call initStaticPackedBuffers first)");
  }
  const totalBytes = resolvedCount * resolvedBytes;
  const src = resolvedBuffers.srcBuffer;
  const dst611 = resolvedBuffers.dstBuffer611;
  const dst612 = resolvedBuffers.dstBuffer612;
  const dstMap = resolvedBuffers.dstBuffers || { 611: dst611, 612: dst612 };

  let currentFrameIndex = 0;
  let lastDestinationBufferId = 611;

  function submitFrame(data, timingRecord = null, targetDestinationId = null) {
    let dstId;
    if (targetDestinationId !== null) {
      if (targetDestinationId === 0) dstId = 611;
      else if (targetDestinationId === 1) dstId = 612;
      else dstId = targetDestinationId;
      if (dstId !== 611 && dstId !== 612) {
        throw new RangeError(`destination must be 611 or 612, got ${targetDestinationId}`);
      }
    } else {
      dstId = (currentFrameIndex % 2 === 0) ? 611 : 612;
    }
    const targetDst = dstMap[dstId];
    lastDestinationBufferId = dstId;
    currentFrameIndex++;
    return executeStaticPackedSubmission(device, src, targetDst, data, dstId, resolvedCount, resolvedBytes, timingRecord);
  }

  return {
    device,
    srcBuffer: src,
    dstBuffer611: dst611,
    dstBuffer612: dst612,
    dstBuffers: dstMap,
    recordCount: resolvedCount,
    byteLength: totalBytes,
    srcBufferId: 610,
    dstBufferIds: [611, 612],
    get currentFrameIndex() { return currentFrameIndex; },
    get lastDestinationBufferId() { return lastDestinationBufferId; },
    submit: (data) => submitFrame(data, null, null),
    submitFrame,
    readback: async (slotOrId = null) => {
      let dstId;
      if (slotOrId === null) dstId = lastDestinationBufferId;
      else if (slotOrId === 0) dstId = 611;
      else if (slotOrId === 1) dstId = 612;
      else dstId = slotOrId;
      if (dstId !== 611 && dstId !== 612) {
        throw new RangeError(`destination must be 611 or 612, got ${slotOrId}`);
      }
      const b = dstMap[dstId];
      await b.mapAsync(GPUMapMode.READ, 0, totalBytes);
      const mapped = b.getMappedRange(0, totalBytes);
      const copy = new Uint8Array(mapped.slice(0));
      b.unmap();
      return copy;
    },
    destroy: () => {
      src.destroy();
      dst611.destroy();
      dst612.destroy();
    },
  };
}

// CLI entry point for RCH execution
if (process.argv[1] && process.argv[1].endsWith('static_submission_generator.mjs')) {
  const targetDir = process.argv[2] || path.resolve('out/browser-probe');
  const targetPath = path.join(targetDir, 'static_submission_4000.js');
  const meta = emitStaticSubmissionModule(targetPath, 4000);
  console.log(`[static_submission_generator] Emitted ${meta.lineCount} lines (${meta.byteLength} bytes) to ${meta.path}`);
  const tailPath = path.join(targetDir, 'static_submission_tail4.js');
  const tailCode = generateStaticSubmissionSource(4, 256, 3996);
  fs.writeFileSync(tailPath, tailCode, 'utf-8');
  console.log(`[static_submission_generator] Emitted ${Buffer.byteLength(tailCode)} bytes to ${tailPath}`);
  const packedPath = path.join(targetDir, 'static_packed_upload_4000.js');
  const packedMeta = emitStaticPackedUploadModule(packedPath, 4000, 48);
  console.log(`[static_submission_generator] Emitted ${packedMeta.lineCount} lines (${packedMeta.byteLength} bytes) to ${packedMeta.path}`);
}
